
(()=>{
const PASSWORD='Trung-Kjrusagki', DB_NAME='reze_library_v10', STORE='items', CHUNKS='chunks';
const MUSIC_KEY='reze_music_enabled', MUSIC_ORDER_KEY='reze_music_order_v1', CAT_ORDER_KEY='reze_category_order_v1', BG_VIDEO_KEY='reze_background_video_id_v1';
const login=document.getElementById('login'),app=document.getElementById('app'),v1=document.getElementById('video1'),v2=document.getElementById('video2'),form=document.getElementById('loginForm'),pw=document.getElementById('password'),status=document.getElementById('loginStatus');
const views=[...document.querySelectorAll('.view')];
const CHUNK_SIZE=512*1024;
let currentView='homeView',currentCat='',editMode=false,rankMode=false,rankFilter='',selected=new Set(),editingId=null,db;
const musicCoverUrls=new Set();
let musicEnabled=localStorage.getItem(MUSIC_KEY)!=='0';
let pendingCover=null, viewerVideo=null, viewerObjectUrl=null, musicEditId=null, pendingMusicCover1=null, pendingMusicCover2=null, musicQueue=[], musicPlayed=new Set(), musicRandom=false, musicCurrentId=null, draggingCat=null;
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,3);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id',autoIncrement:true});if(!d.objectStoreNames.contains(CHUNKS))d.createObjectStore(CHUNKS,{keyPath:['itemId','index']})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
async function getOPFSFile(path){
  if(!path||!navigator.storage?.getDirectory)return null;
  try{const root=await navigator.storage.getDirectory();const fh=await root.getFileHandle(path);return await fh.getFile()}catch(e){return null}
}
async function reqP(req){return new Promise((res,rej)=>{req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)})}
async function chunkPut(itemId,index,data){const tx=db.transaction(CHUNKS,'readwrite');tx.objectStore(CHUNKS).put({itemId,index,data});return new Promise((res,rej)=>{tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error||new Error('CHUNK_WRITE_FAILED'));tx.onabort=()=>rej(tx.error||new Error('CHUNK_WRITE_ABORTED'))})}
async function deleteChunks(itemId){return new Promise((res,rej)=>{const tx=db.transaction(CHUNKS,'readwrite');const req=tx.objectStore(CHUNKS).openCursor(IDBKeyRange.bound([itemId,0],[itemId,Number.MAX_SAFE_INTEGER]));req.onsuccess=e=>{const c=e.target.result;if(c){c.delete();c.continue()}};tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function readChunks(itemId,count,type){const chunks=[];const tx=db.transaction(CHUNKS,'readonly');const store=tx.objectStore(CHUNKS);for(let i=0;i<count;i++){const x=await reqP(store.get([itemId,i]));if(!x)throw new Error('MISSING_CHUNK_'+i);chunks.push(x.data)}return new Blob(chunks,{type:type||'application/octet-stream'})}
async function hydrateItem(item){if(item.chunked&&!item.blob){item.blob=await readChunks(item.id,item.chunkCount,item.type)}else if(item.opfsPath&&!item.blob){item.blob=await getOPFSFile(item.opfsPath)}return item}
async function allItems(){return new Promise((res,rej)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function getItem(id){const raw=await reqP(db.transaction(STORE,'readonly').objectStore(STORE).get(id));if(!raw)throw new Error('ITEM_NOT_FOUND');return hydrateItem(raw)}
const liveUrls=new Set();
function revokeLiveUrls(){for(const u of liveUrls)try{URL.revokeObjectURL(u)}catch(_){}liveUrls.clear()}
async function hydrateGrid(grid){if(!grid)return;const holders=[...grid.querySelectorAll('[data-thumb-id]')];await Promise.all(holders.map(async h=>{try{const item=await getItem(+h.dataset.thumbId);const file=item.coverBlob || item.blob || await (async()=>item.blob||await hydrateItem(item).then(x=>x.blob))();if(!file)return;const url=URL.createObjectURL(file);liveUrls.add(url);if(item.coverBlob || item.type?.startsWith('image/')){const img=document.createElement('img');img.className='thumb';img.src=url;img.alt='';img.loading='lazy';img.decoding='async';img.fetchPriority='low';h.replaceWith(img)}else if(item.type?.startsWith('video/')){const v=document.createElement('video');v.className='thumb';v.src=url;v.muted=true;v.playsInline=true;v.preload='metadata';v.setAttribute('aria-hidden','true');h.replaceWith(v)}else{h.innerHTML='📄'}}catch(e){h.textContent='Không tải được'}}))}
async function writeOPFS(blob,existingPath){
  if(!blob||!navigator.storage?.getDirectory)throw new Error('OPFS_UNAVAILABLE');
  const root=await navigator.storage.getDirectory();
  const path=existingPath||('reze_'+Date.now()+'_'+Math.random().toString(36).slice(2));
  const fh=await root.getFileHandle(path,{create:true});
  const w=await fh.createWritable();
  await w.write(blob);
  await w.close();
  return path;
}
async function put(item){
  const raw=item.id?await reqP(db.transaction(STORE,'readonly').objectStore(STORE).get(item.id)):null;
  if(raw?.chunked||raw?.opfsPath){const copy={...raw,...item};delete copy.blob;return saveMeta(copy)}
  if(raw?.blob){const copy={...raw,...item,blob:raw.blob};return reqP(db.transaction(STORE,'readwrite').objectStore(STORE).put(copy))}
  if(item.blob){return storeFile(new File([item.blob],item.name,{type:item.type||item.blob.type||'application/octet-stream'}),item.category)}
  const copy={...item};delete copy.blob;return saveMeta(copy)
}
async function del(id){const item=await reqP(db.transaction(STORE,'readonly').objectStore(STORE).get(id));if(item?.chunked)try{await deleteChunks(id)}catch(_){}if(item?.opfsPath&&navigator.storage?.getDirectory)try{const root=await navigator.storage.getDirectory();await root.removeEntry(item.opfsPath)}catch(_){}return reqP(db.transaction(STORE,'readwrite').objectStore(STORE).delete(id))}
async function getAppStorageBreakdown(){
  const items=await allItems();
  let images=0,videos=0,files=0,total=0;
  for(const x of items){const n=Number(x.size)||0;total+=n;if(x.type?.startsWith('image/'))images+=n;else if(x.type?.startsWith('video/'))videos+=n;else files+=n}
  return {items,images,videos,files,total};
}
function formatPercent(n){return Number.isFinite(n)?Math.max(0,Math.min(100,n)).toFixed(n>=10?0:1)+'%':'—'}
async function refreshStorageUI(){
  const sub=document.getElementById('storageSub');if(!sub)return;
  const usedEl=document.getElementById('storageUsed'),freeEl=document.getElementById('storageFree'),quotaEl=document.getElementById('storageQuota'),bar=document.getElementById('storageBarFill');
  try{
    const own=await getAppStorageBreakdown();
    document.getElementById('storageImages').textContent=formatSize(own.images);
    document.getElementById('storageVideos').textContent=formatSize(own.videos);
    document.getElementById('storageFiles').textContent=formatSize(own.files);
    let est=null;
    if(navigator.storage?.estimate){try{est=await navigator.storage.estimate()}catch(e){}}
    if(est?.quota){
      const usage=Number(est.usage)||0, quota=Number(est.quota)||0, free=Math.max(0,quota-usage), pct=quota?usage/quota*100:0;
      usedEl.textContent=formatSize(usage);freeEl.textContent=formatSize(free);quotaEl.textContent=formatSize(quota);bar.style.width=Math.min(100,pct)+'%';
      sub.textContent=`Trình duyệt ước tính ${formatPercent(pct)} quota đang được dùng. Số liệu là ước tính.`;
    }else{
      usedEl.textContent=formatSize(own.total);freeEl.textContent='Không xác định';quotaEl.textContent='Không xác định';bar.style.width='0%';
      sub.textContent=`Nội dung của web đang chiếm khoảng ${formatSize(own.total)}. Brave không cung cấp quota ước tính cho địa chỉ HTTP này.`;
    }
  }catch(e){sub.textContent='Không đọc được thông tin bộ nhớ lúc này.';console.error(e)}
}
async function prepareStorage(){try{if(navigator.storage?.persist)await navigator.storage.persist()}catch(e){}try{if(navigator.storage?.estimate){const q=await navigator.storage.estimate();console.log('Storage',q)}}catch(e){}}
async function saveMeta(item){const copy={...item};delete copy.blob;return reqP(db.transaction(STORE,'readwrite').objectStore(STORE).put(copy))}
async function storeFile(file,category){
  if(!file||!category)throw new Error('INVALID_FILE');
  const item={name:file.name.replace(/\.[^.]+$/,'')||file.name,description:'',category,rank:'',type:file.type||'application/octet-stream',size:file.size,createdAt:Date.now(),storage:'pending'};
  try{
    if(navigator.storage?.estimate){const est=await navigator.storage.estimate();const free=Math.max(0,(Number(est.quota)||0)-(Number(est.usage)||0));if(free && file.size>Math.max(0,free-8*1024*1024))throw new Error('STORAGE_SPACE_LOW');}
  }catch(e){if(e?.message==='STORAGE_SPACE_LOW')throw e}
  const id=await reqP(db.transaction(STORE,'readwrite').objectStore(STORE).add(item));
  const statusEl=document.getElementById('uploadStatus');
  try{
    // Prefer OPFS: stream the selected file directly instead of creating one huge Blob in memory.
    if(navigator.storage?.getDirectory){
      let path='reze_'+id+'_'+Date.now()+'_'+Math.random().toString(36).slice(2);
      try{
        const root=await navigator.storage.getDirectory();
        const fh=await root.getFileHandle(path,{create:true});
        const writable=await fh.createWritable();
        const reader=file.stream().getReader();let written=0;
        try{while(true){const {done,value}=await reader.read();if(done)break;await writable.write(value);written+=value.byteLength;if(statusEl)statusEl.textContent=`Đang thêm ${file.name} · ${Math.round(written/file.size*100)}%`}}finally{reader.releaseLock()}
        await writable.close();
        item.opfsPath=path;item.storage='opfs';delete item.chunked;delete item.chunkCount;await saveMeta({...item,id});return id;
      }catch(opfsErr){try{const root=await navigator.storage.getDirectory();await root.removeEntry(path)}catch(_){}console.warn('OPFS failed, falling back to chunks',opfsErr)}
    }
    item.chunked=true;item.chunkCount=Math.max(1,Math.ceil(file.size/CHUNK_SIZE));item.storage='chunks';await saveMeta({...item,id});
    for(let i=0;i<item.chunkCount;i++){const buf=await file.slice(i*CHUNK_SIZE,Math.min(file.size,(i+1)*CHUNK_SIZE)).arrayBuffer();await chunkPut(id,i,buf);if(statusEl)statusEl.textContent=`Đang thêm ${file.name} · ${Math.round((i+1)/item.chunkCount*100)}%`}
    return id;
  }catch(e){
    try{if(item.chunked)await deleteChunks(id)}catch(_){}
    try{if(item.opfsPath&&navigator.storage?.getDirectory){const root=await navigator.storage.getDirectory();await root.removeEntry(item.opfsPath)}}catch(_){}
    try{await reqP(db.transaction(STORE,'readwrite').objectStore(STORE).delete(id))}catch(_){}
    throw e;
  }
}
function showModal(id){document.getElementById(id).classList.add('show')}
function hideModal(id){document.getElementById(id).classList.remove('show');if(id==='viewerModal'){if(viewerVideo){try{viewerVideo.pause()}catch(_){}viewerVideo=null}if(viewerObjectUrl){try{URL.revokeObjectURL(viewerObjectUrl)}catch(_){}viewerObjectUrl=null}document.getElementById('viewer').innerHTML='';const ma=document.getElementById('musicAudio');if(ma&&!ma.paused){stopVideo2Audio();}else ensureVideo2Playing()}}
function escapeHtml(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function formatSize(n){if(!n)return '';const u=['B','KB','MB','GB'];let i=0,x=n;while(x>=1024&&i<u.length-1){x/=1024;i++}return (i?x.toFixed(x>=10?0:1):x.toFixed(0))+' '+u[i]}
function typeLabel(item){if(item.type?.startsWith('image/'))return 'ẢNH';if(item.type?.startsWith('video/'))return 'VIDEO';return 'FILE'}
function formatTime(sec){sec=Number(sec);if(!Number.isFinite(sec)||sec<0)return '0:00';const m=Math.floor(sec/60),s=Math.floor(sec%60);return m+':'+String(s).padStart(2,'0')}
function parseLyrics(raw,duration){const text=String(raw||'').replace(/\r/g,'').trim();if(!text)return [];const lines=text.split('\n').map(x=>x.trim()).filter(Boolean);const timed=[];for(const line of lines){const m=line.match(/^\s*\[(\d{1,2}):(\d{2}(?:\.\d{1,3})?)\]\s*(.*)$/);if(m)timed.push({time:Number(m[1])*60+Number(m[2]),text:m[3]||'♪'});}if(timed.length){timed.sort((a,b)=>a.time-b.time);return timed.map((x,i)=>({time:x.time,text:x.text,end:i+1<timed.length?timed[i+1].time:Math.max(duration||x.time+8,x.time+8)}))}const step=Number(duration)>0?Number(duration)/lines.length:8;return lines.map((text,i)=>({time:i*step,text,end:(i+1)*step}))}
async function renderLyrics(item){const panel=document.getElementById('musicLyrics'),linesEl=document.getElementById('lyricsLines');if(!panel||!linesEl)return;const audio=document.getElementById('musicAudio');document.getElementById('lyricsTitle').textContent=musicMetaName(item);document.getElementById('lyricsAuthor').textContent=musicAuthor(item);const cover=document.getElementById('lyricsCover');if(cover.dataset.url)try{URL.revokeObjectURL(cover.dataset.url)}catch(_){}if(item.coverBlob){const u=URL.createObjectURL(item.coverBlob);cover.dataset.url=u;cover.src=u}else{delete cover.dataset.url;cover.removeAttribute('src')}const parsed=parseLyrics(item.lyrics,audio.duration);linesEl.innerHTML=parsed.length?parsed.map((x,i)=>`<div class="lyric-line" data-lyric-index="${i}">${escapeHtml(x.text)}</div>`).join(''):'<div class="lyrics-empty">Chưa có lyric. Vào Chỉnh sửa bài hát để thêm lời.</div>';panel.classList.remove('hidden');panel._lyrics=parsed;updateLyricsHighlight()}
function updateLyricsHighlight(){const panel=document.getElementById('musicLyrics'),linesEl=document.getElementById('lyricsLines'),audio=document.getElementById('musicAudio');if(!panel||panel.classList.contains('hidden')||!panel._lyrics)return;const t=Number(audio.currentTime)||0;let active=-1;panel._lyrics.forEach((x,i)=>{if(t>=x.time&&(i===panel._lyrics.length-1||t<x.end))active=i});[...linesEl.children].forEach((el,i)=>{el.classList.toggle('active',i===active);el.classList.toggle('past',active>=0&&i<active)});if(active>=0){const el=linesEl.children[active];if(el)panel.scrollTo({top:Math.max(0,el.offsetTop-panel.clientHeight*.35),behavior:'smooth'})}}
async function loadBackgroundVideo(){const key=localStorage.getItem(BG_VIDEO_KEY);if(!key)return;try{const item=await getItem(Number(key));const hydrated=await hydrateItem(item);if(!hydrated.blob)return;const url=URL.createObjectURL(hydrated.blob);v2.dataset.customUrl=url;v2.src=url;document.getElementById('backgroundFileName').textContent='Đang dùng: '+(item.name||'Video nền tùy chỉnh');v2.load()}catch(e){localStorage.removeItem(BG_VIDEO_KEY)}}
async function setBackgroundVideo(file){if(!file||!file.type.startsWith('video/'))return;const oldId=Number(localStorage.getItem(BG_VIDEO_KEY));if(oldId)try{await del(oldId)}catch(_){}const id=await storeFile(file,'Background');localStorage.setItem(BG_VIDEO_KEY,String(id));const item=await getItem(id);const hydrated=await hydrateItem(item);if(hydrated.blob){if(v2.dataset.customUrl)try{URL.revokeObjectURL(v2.dataset.customUrl)}catch(_){}const url=URL.createObjectURL(hydrated.blob);v2.dataset.customUrl=url;v2.src=url;v2.loop=true;v2.currentTime=0;v2.load();await ensureVideo2Playing()}document.getElementById('backgroundFileName').textContent='Đang dùng: '+file.name}
async function resetBackgroundVideo(){const id=Number(localStorage.getItem(BG_VIDEO_KEY));if(id)try{await del(id)}catch(_){}localStorage.removeItem(BG_VIDEO_KEY);if(v2.dataset.customUrl)try{URL.revokeObjectURL(v2.dataset.customUrl)}catch(_){}delete v2.dataset.customUrl;v2.src='./Reze_Yen_Binh.mp4';v2.loop=true;v2.currentTime=0;v2.load();document.getElementById('backgroundFileName').textContent='Đang dùng Reze Yên Bình';await ensureVideo2Playing()}
function syncMusicButton(){const b=document.getElementById('musicToggle'),t=document.getElementById('musicStateText');if(!b)return;b.textContent=musicEnabled?'🔊':'🔇';b.title=musicEnabled?'Tắt nhạc nền':'Bật nhạc nền';if(t)t.textContent=musicEnabled?'Nhạc nền đang bật · Chuyển mục không làm nhạc dừng.':'Nhạc nền đang tắt · Chuyển mục sẽ không tự bật lại âm thanh.';b.classList.toggle('active',!musicEnabled)}
async function getMusicItems(){return (await allItems()).filter(x=>x.category==='Music').sort((a,b)=>(a.musicOrder??a.createdAt)-(b.musicOrder??b.createdAt))}
async function saveMusicOrder(items){for(let i=0;i<items.length;i++){const x=items[i];x.musicOrder=i;await saveMeta(x)}}
async function loadMusicCover(item,key){const b=item?.[key];if(!b)return '';try{return URL.createObjectURL(b)}catch(_){return ''}}
function musicMetaName(item){return item.name||'Không tên'}
function musicAuthor(item){return item.author||'Không rõ tác giả'}
function video2HasMusic(){const a=document.getElementById('musicAudio');return !!(musicCurrentId!==null && a && a.src && !a.paused)}
async function ensureVideo2Playing(){try{v2.loop=true;v2.playsInline=true;v2.preload='auto';if(video2HasMusic() || !musicEnabled){v2.muted=true;v2.volume=0}else{v2.muted=false;v2.volume=1}if(v2.paused)await v2.play()}catch(_){}
}
function stopVideo2Audio(){try{v2.muted=true;v2.volume=0}catch(_){}
}
async function showMiniMusic(item){const mini=document.getElementById('musicMini');if(!mini)return;document.getElementById('miniTitle').textContent=musicMetaName(item);document.getElementById('miniAuthor').textContent=musicAuthor(item);const img=document.getElementById('miniCover');if(img.dataset.url)try{URL.revokeObjectURL(img.dataset.url)}catch(_){}img.dataset.url='';if(item.coverBlob){const u=URL.createObjectURL(item.coverBlob);img.src=u;img.dataset.url=u}else img.removeAttribute('src');mini.classList.remove('hidden','sink');mini.classList.add('linger');document.getElementById('miniPlay').textContent=document.getElementById('musicAudio').paused?'▶':'❚❚';app.classList.add('music-playing')}
async function stopBackgroundVideo(){try{v2.muted=true;v2.volume=0;if(v2.paused)await v2.play()}catch(_){}
}
async function playMusicItem(item,fromRandom=false){if(!item||!musicEnabled)return;const audio=document.getElementById('musicAudio');const raw=await getItem(item.id);if(musicRandom&&!fromRandom)musicPlayed.add(item.id);if(raw?.remoteUrl){if(audio.dataset.url)try{URL.revokeObjectURL(audio.dataset.url)}catch(_){}audio.dataset.url='';audio.src=raw.remoteUrl}else{if(!raw?.blob&&!raw?.opfsPath&&!raw?.chunked)return;const hydrated=await hydrateItem(raw);if(!hydrated.blob)return;const url=URL.createObjectURL(hydrated.blob);if(audio.dataset.url)try{URL.revokeObjectURL(audio.dataset.url)}catch(_){}audio.dataset.url=url;audio.src=url}audio.loop=false;audio.volume=1;musicCurrentId=item.id;await stopBackgroundVideo();showMiniMusic(item);await renderLyrics(item);try{await audio.play()}catch(_){ }renderMusicList()}
async function playNextMusic(){const items=await getMusicItems();if(!items.length)return;if(!musicRandom){let idx=items.findIndex(x=>x.id===musicCurrentId);let next=items[idx+1];if(!next){musicCurrentId=null;document.getElementById('musicAudio').pause();clearMusicProgress();document.getElementById('musicMini')?.classList.add('hidden');app.classList.remove('music-playing');await ensureVideo2Playing();renderMusicList();return}await playMusicItem(next);return}if(musicPlayed.size>=items.length){musicCurrentId=null;document.getElementById('musicAudio').pause();clearMusicProgress();document.getElementById('musicMini')?.classList.add('hidden');app.classList.remove('music-playing');await ensureVideo2Playing();renderMusicList();return}const pool=items.filter(x=>!musicPlayed.has(x.id));if(!pool.length){musicCurrentId=null;document.getElementById('musicAudio').pause();clearMusicProgress();document.getElementById('musicMini')?.classList.add('hidden');app.classList.remove('music-playing');await ensureVideo2Playing();renderMusicList();return}const next=pool[Math.floor(Math.random()*pool.length)];musicPlayed.add(next.id);await playMusicItem(next,true)}
async function toggleMusicPlayback(){const a=document.getElementById('musicAudio');if(!a.src){const items=await getMusicItems();if(!items.length)return;if(musicRandom){musicPlayed.clear();const first=items[Math.floor(Math.random()*items.length)];musicPlayed.add(first.id);await playMusicItem(first,true)}else await playMusicItem(items[0]);return}if(a.paused){try{await a.play();v2.muted=true;v2.volume=0}catch(_){}}else{a.pause();if(musicEnabled){v2.muted=false;v2.volume=1;try{await v2.play()}catch(_){}}}const cur=(await getMusicItems()).find(x=>x.id===musicCurrentId);if(cur)showMiniMusic(cur)}
async function renderMusicList(){const grid=document.getElementById('musicList');for(const u of musicCoverUrls)try{URL.revokeObjectURL(u)}catch(_){}musicCoverUrls.clear();if(!grid)return;const items=await getMusicItems();document.getElementById('musicEmpty').classList.toggle('hidden',items.length>0);if(!items.length){grid.innerHTML='';return}grid.innerHTML=items.map(x=>`<article class="music-row ${x.id===musicCurrentId?'playing':''}" data-music-id="${x.id}"><div class="music-row-bg" ${x.coverBlob?`style="background-image:url('${(musicCoverUrls.add(URL.createObjectURL(x.coverBlob)),[...musicCoverUrls].at(-1))}')"`:''}></div>${x.coverBlob?`<img class="music-main-cover" src="${(musicCoverUrls.add(URL.createObjectURL(x.coverBlob)),[...musicCoverUrls].at(-1))}" alt="">`:'<div class="music-main-cover"></div>'}<div class="music-info"><div class="music-title">${escapeHtml(musicMetaName(x))}</div><div class="music-author">${escapeHtml(musicAuthor(x))}</div></div>${x.coverBlob2?`<img class="music-secondary" src="${(musicCoverUrls.add(URL.createObjectURL(x.coverBlob2)),[...musicCoverUrls].at(-1))}" alt="">`:''}<button class="music-edit" data-music-edit="${x.id}" type="button" aria-label="Sửa">✎</button><button class="music-delete" data-music-delete="${x.id}" type="button" aria-label="Xóa">🗑</button><button class="music-play" data-music-play="${x.id}" type="button" aria-label="Phát">${x.id===musicCurrentId&&!document.getElementById('musicAudio').paused?'❚❚':'▶'}</button></article>`).join('')}
async function openMusicEdit(item){musicEditId=item.id;pendingMusicCover1=item.coverBlob||null;pendingMusicCover2=item.coverBlob2||null;document.getElementById('musicEditName').value=item.name||'';document.getElementById('musicEditAuthor').value=item.author||'';document.getElementById('musicEditLyrics').value=item.lyrics||'';setMusicPreview('musicCover1Preview',pendingMusicCover1);setMusicPreview('musicCover2Preview',pendingMusicCover2);showModal('musicEditModal')}
function setMusicPreview(id,b){const p=document.getElementById(id);if(p.dataset.url)try{URL.revokeObjectURL(p.dataset.url)}catch(_){}delete p.dataset.url;if(b){const u=URL.createObjectURL(b);p.dataset.url=u;p.src=u;p.classList.remove('hidden')}else{p.removeAttribute('src');p.classList.add('hidden')}}
let musicSearchTimer=0;
async function renderMusicSearch(q){const box=document.getElementById('musicSearchResults');if(!box)return;box.innerHTML='';if(!q)return;box.innerHTML='<div class="cover-note">Đang tìm…</div>';try{const r=await fetch('https://itunes.apple.com/search?term='+encodeURIComponent(q)+'&media=music&entity=song&limit=8');const d=await r.json();box.innerHTML=d.results?.length?d.results.map(x=>`<div class="search-result"><img src="${escapeHtml(x.artworkUrl100||'')}" alt=""><div class="search-result-info"><b>${escapeHtml(x.trackName||'')}</b><span>${escapeHtml(x.artistName||'')} · ${escapeHtml(x.collectionName||'')}</span></div>${x.previewUrl?`<button type="button" data-preview-url="${escapeHtml(x.previewUrl)}" data-preview-name="${escapeHtml(x.trackName||'')}" data-preview-author="${escapeHtml(x.artistName||'')}">▶</button><button type="button" data-preview-add="1" data-preview-url="${escapeHtml(x.previewUrl)}" data-preview-name="${escapeHtml(x.trackName||'')}" data-preview-author="${escapeHtml(x.artistName||'')}" data-preview-cover="${escapeHtml(x.artworkUrl100||'')}">＋</button>`:''}</div>`).join(''):'<div class="cover-note">Không tìm thấy.</div>'}catch(e){box.innerHTML='<div class="cover-note">Không thể tìm kiếm online lúc này. Hãy thử lại hoặc tải file audio lên.</div>'}}
function closeMusicSearch(){const p=document.getElementById('musicSearchPanel');if(p)p.classList.add('hidden');const q=document.getElementById('musicWebQuery');if(q)q.value='';const r=document.getElementById('musicSearchResults');if(r)r.innerHTML=''}
function stopVideo1(){try{v1.pause();v1.muted=true;v1.volume=0;v1.currentTime=0;v1.removeAttribute('src');v1.load()}catch(e){}document.getElementById('video1SoundHint')?.classList.add('hidden')}

let audioCtx=null,lastUiSoundAt=0;
function uiSound(kind='tap'){try{const now=performance.now();if(now-lastUiSoundAt<55)return;lastUiSoundAt=now;if(!window.AudioContext&&!window.webkitAudioContext)return;audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=kind==='open'?620:kind==='nav'?480:720;g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.035,audioCtx.currentTime+.008);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.085);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.09)}catch(e){}}
function playViewTransition(title,isCategory=false){const el=document.getElementById('viewTransition'),t=document.getElementById('vtTitle');t.textContent=title;t.classList.toggle('long-category',!!isCategory&&String(title).length>14);el.classList.toggle('category-mode',!!isCategory);el.classList.remove('run');void el.offsetWidth;el.classList.add('run');setTimeout(()=>el.classList.remove('run'),isCategory?1100:780)}
const NOTES_KEY='reze_home_notes_v1';
function getHomeNotes(){try{const a=JSON.parse(localStorage.getItem(NOTES_KEY)||'[]');return Array.isArray(a)?a.filter(x=>typeof x==='string'&&x.trim()):[]}catch(_){return []}}
function saveHomeNotes(a){localStorage.setItem(NOTES_KEY,JSON.stringify(a.slice(0,100)))}
function cleanNoteText(v){return String(v||'').trim().replace(/^[“”"']+|[“”"']+$/g,'').trim()}
function showRandomHomeQuote(){const el=document.getElementById('homeQuote');if(!el)return;const notes=getHomeNotes();if(!notes.length){el.classList.add('hidden');el.innerHTML='';return}const chosen=cleanNoteText(notes[Math.floor(Math.random()*notes.length)]);el.classList.remove('hidden');el.innerHTML='<span class="quote-text">&quot; '+escapeHtml(chosen)+'&quot;</span>';el.classList.remove('quote-refresh');void el.offsetWidth;el.classList.add('quote-refresh')}
function renderHomeNotes(){const list=document.getElementById('notesList');if(!list)return;const notes=getHomeNotes();list.innerHTML=notes.length?notes.map((x,i)=>`<div class="note-item" data-note-row="${i}"><span class="note-display">${escapeHtml(cleanNoteText(x))}</span><textarea class="note-edit-input hidden" rows="2">${escapeHtml(cleanNoteText(x))}</textarea><div class="note-actions"><button type="button" data-note-edit="${i}" aria-label="Chỉnh sửa câu">✎</button><button type="button" data-note-save="${i}" class="hidden" aria-label="Lưu câu">✓</button><button type="button" data-note-cancel="${i}" class="hidden" aria-label="Hủy">×</button><button type="button" data-note-del="${i}" aria-label="Xóa câu">⌫</button></div></div>`).join(''):'<div class="notes-empty">Chưa có câu nào. Thêm vài câu để các đề mục chọn ngẫu nhiên.</div>'}
function bindHomeNotes(){const viewBtn=document.getElementById('notesViewBtn'),savedPanel=document.getElementById('notesSavedPanel');if(viewBtn&&savedPanel){viewBtn.onclick=()=>{savedPanel.classList.toggle('hidden');viewBtn.textContent=savedPanel.classList.contains('hidden')?'Xem':'Ẩn';uiSound('tap')}}const add=document.getElementById('noteAddBtn'),input=document.getElementById('noteInput'),list=document.getElementById('notesList');if(!add||!input||!list)return;add.onclick=()=>{const value=cleanNoteText(input.value);if(!value)return;const notes=getHomeNotes();notes.push(value);saveHomeNotes(notes);input.value='';renderHomeNotes();showRandomHomeQuote();uiSound('tap')};input.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')add.click()});list.onclick=e=>{const edit=e.target.closest('[data-note-edit]'),save=e.target.closest('[data-note-save]'),cancel=e.target.closest('[data-note-cancel]'),del=e.target.closest('[data-note-del]');const row=e.target.closest('[data-note-row]');if(!row)return;const i=Number(row.dataset.noteRow);const notes=getHomeNotes();if(edit){uiSound('tap');row.querySelector('.note-display')?.classList.add('hidden');row.querySelector('.note-edit-input')?.classList.remove('hidden');row.querySelector('[data-note-edit]')?.classList.add('hidden');row.querySelector('[data-note-del]')?.classList.add('hidden');row.querySelector('[data-note-save]')?.classList.remove('hidden');row.querySelector('[data-note-cancel]')?.classList.remove('hidden');row.querySelector('.note-edit-input')?.focus();return}if(save){const v=cleanNoteText(row.querySelector('.note-edit-input')?.value);if(!v)return;notes[i]=v;saveHomeNotes(notes);renderHomeNotes();showRandomHomeQuote();uiSound('tap');return}if(cancel){renderHomeNotes();return}if(del){notes.splice(i,1);saveHomeNotes(notes);renderHomeNotes();showRandomHomeQuote();uiSound('tap')}};renderHomeNotes()}
bindHomeNotes();
function switchView(id){const labels={homeView:'Home',searchView:'Search',musicView:'Music',achievementsView:'Achievements',youView:'You',categoryView:currentCat||'Category'};const wasMusic=currentView==='musicView'&&id!=='musicView';uiSound('nav');showRandomHomeQuote();playViewTransition(labels[id]||'',id==='categoryView');currentView=id;views.forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'auto'});document.documentElement.scrollTop=0;document.body.scrollTop=0;if(id!=='categoryView'){editMode=false;rankMode=false;selected.clear();document.getElementById('categoryView').classList.remove('edit-on','rank-mode')}closeMusicSearch();syncMusicButton();ensureVideo2Playing();if(wasMusic){const mini=document.getElementById('musicMini');if(mini&&!mini.classList.contains('hidden')){mini.classList.remove('sink');mini.classList.add('linger');clearTimeout(window.__miniSinkTimer);window.__miniSinkTimer=setTimeout(()=>{mini.classList.remove('linger');mini.classList.add('sink');setTimeout(()=>{mini.classList.add('hidden');app.classList.remove('music-playing')},600)},2000)}}if(id==='musicView'){const mini=document.getElementById('musicMini');if(mini&&!document.getElementById('musicAudio').paused){mini.classList.remove('hidden','sink');mini.classList.add('linger');app.classList.add('music-playing')}}if(id==='youView')refreshStorageUI();if(id==='musicView'){syncAllSameNameMusic().then(()=>renderMusicList())}}
function makeThumb(item){if(item.coverBlob || item.blob){return `<div class="thumb media-placeholder" data-thumb-id="${item.id}">${item.type?.startsWith('video/')?'VIDEO':item.type?.startsWith('image/')?'ẢNH':'📄'}</div>`}if(item.type?.startsWith('image/'))return `<div class="thumb media-placeholder" data-thumb-id="${item.id}">ẢNH</div>`;if(item.type?.startsWith('video/'))return `<div class="thumb media-placeholder" data-thumb-id="${item.id}">VIDEO</div>`;return `<div class="thumb media-placeholder" data-thumb-id="${item.id}" style="display:grid;place-items:center;font-size:36px">📄</div>`}
function card(item,opts={}){const rank=item.rank?`<span class="rank-badge ${item.rank.toLowerCase()}">${item.rank}</span>`:'';const add=opts.rankMode?`<button class="rank-add" data-rank-add="${item.id}" title="Thêm vào ${rankFilter}">＋</button>`:'';const desc=item.description?`<div class="desc">${escapeHtml(item.description)}</div>`:'';const fileInfo=!item.type?.startsWith('image/')&&!item.type?.startsWith('video/')?`<div class="file-info"><span>${escapeHtml(item.type||'File')}</span><span>${formatSize(item.size||item.blob?.size)}</span></div>`:'';return `<article class="media-card ${selected.has(item.id)?'selected':''}" data-id="${item.id}" style="--i:${opts.index||0}">${makeThumb(item)}${rank}${add}<span class="type-badge">${typeLabel(item)}</span><input class="check" type="checkbox" data-check="${item.id}" ${selected.has(item.id)?'checked':''}><div class="meta"><div class="name">${escapeHtml(item.name)}</div>${desc}<div class="sub">${escapeHtml(item.category)} · ${new Date(item.createdAt).toLocaleDateString('vi-VN')}</div>${fileInfo}</div></article>`}
async function renderCategory(){revokeLiveUrls();const items=(await allItems()).filter(x=>x.category===currentCat);let shown=items;if(currentCat==='NSFW'&&rankFilter)shown=items.filter(x=>x.rank===rankFilter);document.getElementById('catEyebrow').textContent=currentCat.toUpperCase();document.getElementById('catTitle').textContent=currentCat;document.getElementById('catDesc').textContent=currentCat==='NSFW'?'Kho NSFW — chọn SSR / S / A / B / C để lọc.':'Kho nội dung riêng của mày.';document.getElementById('rankTabs').classList.toggle('hidden',currentCat!=='NSFW');document.getElementById('rankTabs').querySelectorAll('.rank-tab').forEach(b=>b.classList.toggle('active',b.dataset.rank===rankFilter));const grid=document.getElementById('mediaGrid');grid.innerHTML=shown.length?shown.map((x,i)=>card(x,{rankMode:rankMode&&currentCat==='NSFW',index:i})).join(''):'';document.getElementById('empty').classList.toggle('hidden',shown.length>0);document.getElementById('toolbar').querySelector('#selectedCount').textContent=selected.size+' đã chọn';document.getElementById('categoryView').classList.toggle('edit-on',editMode);document.getElementById('categoryView').classList.toggle('rank-mode',rankMode);await hydrateGrid(grid)}
async function renderSearch(){revokeLiveUrls();const q=document.getElementById('searchInput').value.trim().toLowerCase();const items=(await allItems()).filter(x=>x.category!=='Background');const shown=q?items.filter(x=>(x.name+' '+(x.description||'')+' '+x.category).toLowerCase().includes(q)):items;const grid=document.getElementById('searchGrid');grid.innerHTML=shown.length?shown.map((x,i)=>card(x,{index:i})).join(''):'<div class="empty" style="grid-column:1/-1">Không tìm thấy.</div>';await hydrateGrid(grid)}
async function renderAchievements(){revokeLiveUrls();const items=(await allItems()).filter(x=>x.category==='Achievements');document.getElementById('achievementGrid').innerHTML=items.map((x,i)=>card(x,{index:i})).join('');document.getElementById('achievementEmpty').classList.toggle('hidden',items.length>0);await hydrateGrid(document.getElementById('achievementGrid'))}
function goHome(){switchView('homeView')}
function openCategory(cat){currentCat=cat;rankFilter='';rankMode=false;editMode=false;selected.clear();switchView('categoryView');renderCategory()}
async function openItem(item){
  const viewer=document.getElementById('viewer');
  if(viewerVideo){try{viewerVideo.pause()}catch(_){}viewerVideo=null}
  if(viewerObjectUrl){try{URL.revokeObjectURL(viewerObjectUrl)}catch(_){}viewerObjectUrl=null}
  const ma=document.getElementById('musicAudio');if(ma){try{ma.pause()}catch(_){} }
  if(item.type?.startsWith('video/')){
    v2.muted=true;v2.volume=0;
    viewerObjectUrl=URL.createObjectURL(item.blob);
    viewer.innerHTML=`<div style="text-align:center"><video id="activeViewerVideo" src="${viewerObjectUrl}" controls autoplay playsinline webkit-playsinline preload="auto"></video><div style="margin-top:10px;color:#aaa;font-size:11px">${escapeHtml(item.description||'')}</div></div>`;
    viewerVideo=document.getElementById('activeViewerVideo');
    viewerVideo.muted=false;viewerVideo.volume=1;
    try{await viewerVideo.play()}catch(_){viewerVideo.controls=true}
  }else if(item.type?.startsWith('image/')){
    viewerObjectUrl=URL.createObjectURL(item.blob);
    viewer.innerHTML=`<div style="text-align:center"><img src="${viewerObjectUrl}" alt="${escapeHtml(item.name)}" decoding="async"><div style="margin-top:10px;color:#aaa;font-size:11px">${escapeHtml(item.description||'')}</div></div>`;
  }else{
    viewerObjectUrl=URL.createObjectURL(item.blob);
    viewer.innerHTML=`<div class="panel viewer-file"><h2>${escapeHtml(item.name)}</h2><p style="color:#999">${escapeHtml(item.description||item.type||'File')}</p><a href="${viewerObjectUrl}" download="${escapeHtml(item.name)}"><button>Tải file</button></a></div>`;
  }
  showModal('viewerModal');
}
async function openEditModal(item){editingId=item.id;pendingCover=item.coverBlob||null;document.getElementById('editName').value=item.name||'';document.getElementById('editDesc').value=item.description||'';document.getElementById('editCategory').value=item.category;document.getElementById('editRank').value=item.rank||'';document.getElementById('rankEditField').style.display=item.category==='NSFW'?'block':'none';const preview=document.getElementById('coverPreview');if(preview.dataset.url){try{URL.revokeObjectURL(preview.dataset.url)}catch(_){}}delete preview.dataset.url;if(pendingCover){const u=URL.createObjectURL(pendingCover);preview.dataset.url=u;preview.src=u;preview.classList.remove('hidden')}else{preview.removeAttribute('src');preview.classList.add('hidden')}showModal('editModal')}
function clearCoverPreview(){const p=document.getElementById('coverPreview');if(p.dataset.url){try{URL.revokeObjectURL(p.dataset.url)}catch(_){}}delete p.dataset.url;p.removeAttribute('src');p.classList.add('hidden')}
async function handleGridClick(e){const rankAdd=e.target.closest('[data-rank-add]');if(rankAdd){e.stopPropagation();const id=+rankAdd.dataset.rankAdd;const item=(await allItems()).find(x=>x.id===id);if(item){item.rank=rankFilter;await put(item);renderCategory()}return}const check=e.target.closest('[data-check]');if(check){e.stopPropagation();const id=+check.dataset.check;if(check.checked)selected.add(id);else selected.delete(id);renderCategory();return}const cardEl=e.target.closest('.media-card');if(!cardEl)return;const id=+cardEl.dataset.id;const item=(await allItems()).find(x=>x.id===id);if(!item)return;if(editMode){await openEditModal(await getItem(id))}else{uiSound('open');openItem(await getItem(id))}}
async function addFiles(fileList,category){if(!category){alert('Hãy mở một danh mục trước khi thêm nội dung.');return 0}const files=[...fileList];if(!files.length)return 0;let added=0,failed=[];await prepareStorage();for(const file of files){try{await storeFile(file,category);added++}catch(err){failed.push(file.name);console.error('Upload failed',file.name,err)}}await renderCategory();await renderSearch();await renderAchievements();if(failed.length){const reason=failed.length===files.length?'\n\nCó thể quota của website đã gần đầy. Vào You → Bộ nhớ website để kiểm tra.':'';alert(`Đã thêm ${added}/${files.length} tệp.\nKhông thêm được: ${failed.join(', ')}${reason}`)}return added}
function openPicker(input){try{if(typeof input.showPicker==='function')input.showPicker();else input.click()}catch(e){input.click()}}
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>hideModal(b.dataset.close)));
document.getElementById('addBtn').onclick=()=>{document.getElementById('uploadCategoryLabel').textContent=currentCat||'danh mục hiện tại';document.getElementById('uploadStatus').textContent='';showModal('uploadModal')};
document.getElementById('mediaChoice').onclick=()=>openPicker(document.getElementById('mediaInput'));
document.getElementById('fileChoice').onclick=()=>openPicker(document.getElementById('fileInput'));
document.getElementById('mediaInput').onchange=async e=>{const files=e.target.files;if(files?.length){document.getElementById('uploadStatus').textContent='Đang thêm '+files.length+' tệp…';const added=await addFiles(files,currentCat);document.getElementById('uploadStatus').textContent=added===files.length?`Đã thêm ${added} tệp.`:`Đã thêm ${added}/${files.length} tệp.`;if(added===files.length)setTimeout(()=>hideModal('uploadModal'),450)}e.target.value=''};
document.getElementById('fileInput').onchange=async e=>{const files=e.target.files;if(files?.length){document.getElementById('uploadStatus').textContent='Đang thêm '+files.length+' tệp…';const added=await addFiles(files,currentCat);document.getElementById('uploadStatus').textContent=added===files.length?`Đã thêm ${added} tệp.`:`Đã thêm ${added}/${files.length} tệp.`;if(added===files.length)setTimeout(()=>hideModal('uploadModal'),450)}e.target.value=''};
document.getElementById('coverPickBtn').onclick=()=>openPicker(document.getElementById('coverInput'));document.getElementById('coverRemoveBtn').onclick=()=>{pendingCover=null;clearCoverPreview()};document.getElementById('coverInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/')){alert('Chọn một file ảnh làm ảnh bìa.');e.target.value='';return}pendingCover=new Blob([await f.arrayBuffer()],{type:f.type});const p=document.getElementById('coverPreview');if(p.dataset.url){try{URL.revokeObjectURL(p.dataset.url)}catch(_){}}const u=URL.createObjectURL(pendingCover);p.dataset.url=u;p.src=u;p.classList.remove('hidden');e.target.value=''};
document.getElementById('editBtn').onclick=()=>{editMode=!editMode;rankMode=false;selected.clear();renderCategory()};
document.getElementById('selectAllBtn').onclick=async()=>{const items=(await allItems()).filter(x=>x.category===currentCat&&(currentCat!=='NSFW'||!rankFilter||x.rank===rankFilter));items.forEach(x=>selected.add(x.id));renderCategory()};
document.getElementById('bulkDeleteBtn').onclick=async()=>{if(!selected.size)return;if(!confirm('Xóa '+selected.size+' nội dung đã chọn?'))return;for(const id of selected)await del(id);selected.clear();await renderCategory();renderSearch();renderAchievements()};
document.getElementById('bulkEditBtn').onclick=async()=>{if(selected.size!==1){alert('Hãy chọn đúng 1 nội dung để sửa chi tiết. Muốn xóa nhiều thì dùng Xóa.');return}await openEditModal(await getItem([...selected][0]));};
document.getElementById('saveEditBtn').onclick=async()=>{const item=await getItem(editingId);if(!item)return;item.name=document.getElementById('editName').value.trim()||item.name;item.description=document.getElementById('editDesc').value.trim();item.category=document.getElementById('editCategory').value;item.rank=item.category==='NSFW'?document.getElementById('editRank').value:'';if(pendingCover===null)delete item.coverBlob;else item.coverBlob=pendingCover;await put(item);clearCoverPreview();pendingCover=null;hideModal('editModal');selected.clear();await renderCategory();renderSearch();renderAchievements()};
document.getElementById('rankTabs').onclick=async e=>{const b=e.target.closest('.rank-tab');if(!b)return;uiSound('tap');rankFilter=rankFilter===b.dataset.rank?'':b.dataset.rank;if(editMode)rankMode=true;await renderCategory()};
document.getElementById('mediaGrid').onclick=handleGridClick;document.getElementById('searchGrid').onclick=handleGridClick;document.getElementById('achievementGrid').onclick=handleGridClick;document.getElementById('searchInput').oninput=renderSearch;
document.querySelectorAll('.category-card[data-cat]').forEach(b=>b.onclick=()=>{uiSound('nav');playViewTransition(b.dataset.cat);history.replaceState(null,'','#category:'+encodeURIComponent(b.dataset.cat));openCategory(b.dataset.cat)});
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{const id=b.dataset.view;const map={homeView:'home',searchView:'search',musicView:'music',achievementsView:'achievements',youView:'you'};if(map[id])history.replaceState(null,'','#'+map[id]);switchView(id);if(id==='searchView')renderSearch();if(id==='achievementsView')renderAchievements()});
document.getElementById('musicToggle').onclick=async()=>{const ma=document.getElementById('musicAudio');musicEnabled=!musicEnabled;localStorage.setItem(MUSIC_KEY,musicEnabled?'1':'0');if(!musicEnabled){if(ma&&!ma.paused){window.__musicPausedByToggle=true;window.__musicPausedAt=ma.currentTime;try{ma.pause()}catch(_){} }v2.muted=true;v2.volume=0;}else{if(window.__musicPausedByToggle&&ma&&ma.src&&musicCurrentId!==null){window.__musicPausedByToggle=false;try{if(Number.isFinite(window.__musicPausedAt))ma.currentTime=window.__musicPausedAt}catch(_){}try{await ma.play();v2.muted=true;v2.volume=0}catch(_){}}else{v2.muted=false;v2.volume=1;try{await v2.play()}catch(_){}}}syncMusicButton();renderMusicList();};
document.getElementById('storageRefresh').onclick=refreshStorageUI;
const categoryGrid=document.getElementById('categoryGrid');
const categorySortExit=document.getElementById('categorySortExit');
let sortPointerId=null,sortDragEl=null,sortGhost=null,sortPlaceholder=null,sortLongPressTimer=0,sortStartX=0,sortStartY=0,sortDragOffsetY=0,sortFixedLeft=0,sortActive=false,sortJustActivated=false,sortModeArmed=false;
function clearSortPush(){categoryGrid.querySelectorAll('.push-up,.push-down').forEach(x=>x.classList.remove('push-up','push-down'))}
function exitCategorySort(save=true){clearTimeout(sortLongPressTimer);if(sortDragEl){sortDragEl.style.visibility='';sortDragEl.classList.remove('dragging-source');try{if(sortPointerId!=null&&sortDragEl.hasPointerCapture(sortPointerId))sortDragEl.releasePointerCapture(sortPointerId)}catch(_){}if(sortPlaceholder&&sortPlaceholder.parentNode){categoryGrid.insertBefore(sortDragEl,sortPlaceholder);sortPlaceholder.remove()}}if(sortGhost){sortGhost.remove();sortGhost=null}clearSortPush();sortPlaceholder=null;sortDragEl=null;sortPointerId=null;sortActive=false;sortJustActivated=false;categoryGrid.classList.remove('sorting');categorySortExit.classList.add('hidden');sortModeArmed=false;if(save)localStorage.setItem(CAT_ORDER_KEY,JSON.stringify([...categoryGrid.querySelectorAll('.category-card[data-cat]')].map(x=>x.dataset.cat)));uiSound('tap')}
function enterCategorySort(el,e){if(sortActive)return;sortActive=true;sortJustActivated=true;categoryGrid.classList.add('sorting');categorySortExit.classList.remove('hidden');uiSound('open');sortDragEl=el;sortPointerId=e.pointerId;const r=el.getBoundingClientRect();sortStartX=e.clientX;sortStartY=e.clientY;sortDragOffsetY=e.clientY-r.top;sortFixedLeft=r.left;sortPlaceholder=document.createElement('div');sortPlaceholder.className='category-card drag-placeholder';sortPlaceholder.style.height=r.height+'px';sortPlaceholder.style.width=r.width+'px';sortPlaceholder.setAttribute('aria-hidden','true');el.parentNode.insertBefore(sortPlaceholder,el);el.classList.add('dragging-source');sortGhost=el.cloneNode(true);sortGhost.classList.remove('dragging-source');sortGhost.classList.add('sort-ghost');sortGhost.style.width=r.width+'px';sortGhost.style.height=r.height+'px';sortGhost.style.left=r.left+'px';sortGhost.style.top=r.top+'px';document.body.appendChild(sortGhost);el.style.visibility='hidden';try{el.setPointerCapture(e.pointerId)}catch(_){}e.preventDefault();e.stopPropagation()}
function moveCategorySort(e){if(!sortActive||sortPointerId!==e.pointerId||!sortDragEl||!sortPlaceholder||!sortGhost)return;e.preventDefault();e.stopPropagation();const y=e.clientY;const h=sortGhost.offsetHeight;sortGhost.style.left=sortFixedLeft+'px';sortGhost.style.top=(y-sortDragOffsetY)+'px';const cards=[...categoryGrid.querySelectorAll('.category-card')].filter(x=>x!==sortDragEl&&x!==sortPlaceholder);let target=null;for(const c of cards){const cr=c.getBoundingClientRect();if(y<cr.top+cr.height/2){target=c;break}}clearSortPush();if(target){categoryGrid.insertBefore(sortPlaceholder,target);target.classList.add('push-down')}else{categoryGrid.appendChild(sortPlaceholder);const prev=cards[cards.length-1];if(prev)prev.classList.add('push-up')}}
categoryGrid.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;const el=e.target.closest('.category-card[data-cat]');if(!el)return;sortStartX=e.clientX;sortStartY=e.clientY;clearTimeout(sortLongPressTimer);if(sortModeArmed&&!sortActive){enterCategorySort(el,e);return}});
categoryGrid.addEventListener('pointermove',e=>{if(sortActive){moveCategorySort(e);return}});
categoryGrid.addEventListener('pointerup',e=>{if(sortActive){sortJustActivated=false;return}clearTimeout(sortLongPressTimer)});
categoryGrid.addEventListener('pointercancel',e=>{if(sortActive){exitCategorySort(true);return}clearTimeout(sortLongPressTimer)});
categoryGrid.addEventListener('click',e=>{if(sortActive){e.preventDefault();e.stopPropagation();return}},true);
categoryGrid.addEventListener('contextmenu',e=>{if(e.target.closest('.category-card'))e.preventDefault()});
categorySortExit.onclick=()=>exitCategorySort(true);
const categorySortBtn=document.getElementById('categorySortBtn');
categorySortBtn.onclick=()=>{
  sortModeArmed=true;
  if(currentView!=='homeView')switchView('homeView');
  categoryGrid.classList.add('sorting');
  categorySortExit.classList.remove('hidden');
  setTimeout(()=>{const first=categoryGrid.querySelector('.category-card[data-cat]');if(first)first.scrollIntoView({behavior:'smooth',block:'center'})},80);
  uiSound('open');
};
applyCategoryOrder();
// Music controls
function cleanMusicDisplayName(s){
  let x=String(s||'').replace(/\.[a-z0-9]{2,6}$/i,'').trim();
  x=x.replace(/[\[\(\{][^\]\)\}]*?(?:review|preview|snippet|demo|teaser|full|official|audio|video|lyrics?|lyric|hq|original)[^\]\)\}]*[\]\)\}]/gi,' ');
  x=x.replace(/(?:^|[\s._-])(?:review|preview|snippet|demo|teaser|full|official|audio|video|lyrics?|lyric|hq|original)(?=$|[\s._-])/gi,' ');
  return x.replace(/[_|]+/g,' ').replace(/\s+/g,' ').trim();
}
function normalizeMusicKey(s){
  let x=String(s||'').normalize('NFKC').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  x=x.replace(/\.[a-z0-9]{2,6}$/i,'');
  x=x.replace(/[\[\(\{][^\]\)\}]*?(?:review|preview|snippet|demo|teaser|full|official|audio|video|lyrics?|lyric|hq|original)[^\]\)\}]*[\]\)\}]/gi,' ');
  x=x.replace(/(?:^|[\s._-])(?:review|preview|snippet|demo|teaser|full|official|audio|video|lyrics?|lyric|hq|original)(?=$|[\s._-])/gi,' ');
  x=x.replace(/[‘’´`]/g,"'").replace(/[“”]/g,'"');
  x=x.replace(/[_|]+/g,' ');
  x=x.replace(/[^a-z0-9'&]+/g,' ').trim().replace(/\s+/g,' ');
  return x;
}
function musicHasLocalAudio(item){return !!item && !item.remoteUrl && ((Number(item.size)||0)>0 || !!item.opfsPath || !!item.chunked || !!item.blob)}
function musicIsReview(item){
  if(!item)return false;
  const n=String(item.name||'');
  return !!item.remoteUrl || item.source==='review' || /(?:^|[\s_\-\[\(])(?:review|preview|snippet|demo|teaser)(?:$|[\s_\-\]\)])/i.test(n) || /preview|review/i.test(String(item.description||''));
}
function musicFullScore(item){
  let score=0;
  if(musicHasLocalAudio(item))score+=100;
  if(!musicIsReview(item))score+=20;
  if(/(?:^|[\s_\-\[\(])full(?:$|[\s_\-\]\)])/i.test(String(item.name||'')))score+=15;
  if(/(?:official|original|hq|flac|wav|lossless)/i.test(String(item.name||'')))score+=3;
  if(musicIsReview(item))score-=100;
  return score;
}
function musicMetaRichness(item){return (item?.coverBlob?4:0)+(item?.coverBlob2?2:0)+(item?.lyrics?3:0)+(item?.author?2:0)+(item?.description?1:0)}
function itemLooksLikeReviewName(name){return /(?:^|[\s_\-\[\(])(?:review|preview|snippet|demo|teaser)(?:$|[\s_\-\]\)])/i.test(String(name||''))}
function musicNameSame(a,b){const x=normalizeMusicKey(a),y=normalizeMusicKey(b);return !!x&&!!y&&x===y}
async function findMusicSameName(name){const key=normalizeMusicKey(name);if(!key)return [];return (await getMusicItems()).filter(x=>normalizeMusicKey(x.name)===key)}
async function syncAllSameNameMusic(){
  const items=await getMusicItems();
  const groups=new Map();
  for(const item of items){
    const key=normalizeMusicKey(item.name);
    if(!key)continue;
    if(!groups.has(key))groups.set(key,[]);
    groups.get(key).push(item);
  }
  let removed=0;
  for(const group of groups.values()){
    if(group.length<2)continue;
    const locals=group.filter(musicHasLocalAudio);
    const canonical=(locals.length?locals:group).slice().sort((a,b)=>
      (musicFullScore(b)-musicFullScore(a))||
      (musicMetaRichness(b)-musicMetaRichness(a))||
      ((Number(b.size)||0)-(Number(a.size)||0))||
      ((b.createdAt||0)-(a.createdAt||0))
    )[0];
    const metaSource=group.slice().sort((a,b)=>
      (musicMetaRichness(b)-musicMetaRichness(a))||((b.createdAt||0)-(a.createdAt||0))
    )[0];
    const oldCurrent=group.find(x=>x.id===musicCurrentId);
    const audio=document.getElementById('musicAudio');
    const oldTime=oldCurrent&&audio?.src?(audio.currentTime||0):0;
    if(metaSource && metaSource.id!==canonical.id){
      canonical.name=metaSource.name||canonical.name;
      canonical.author=metaSource.author||canonical.author||'Không rõ tác giả';
      canonical.description=metaSource.description||canonical.description||'';
      canonical.lyrics=metaSource.lyrics||canonical.lyrics||'';
      if(!canonical.coverBlob&&metaSource.coverBlob)canonical.coverBlob=metaSource.coverBlob;
      if(!canonical.coverBlob2&&metaSource.coverBlob2)canonical.coverBlob2=metaSource.coverBlob2;
      if(canonical.musicOrder==null&&metaSource.musicOrder!=null)canonical.musicOrder=metaSource.musicOrder;
    }
    canonical.name=cleanMusicDisplayName(canonical.name)||canonical.name;
    if(locals.length){canonical.source='full';canonical.remoteUrl='';canonical.syncedAt=Date.now()}
    await saveMeta(canonical);
    for(const other of group){
      if(other.id===canonical.id)continue;
      try{await del(other.id);removed++}catch(e){console.error('Music dedupe delete failed',other.id,e)}
    }
    if(oldCurrent && oldCurrent.id!==canonical.id){
      musicCurrentId=canonical.id;
      try{await playMusicItem(canonical);if(oldTime>0&&audio)audio.currentTime=Math.min(oldTime,audio.duration||oldTime)}catch(_){ }
    }
  }
  return removed;
}
async function saveOrSyncMusicFile(file,authorHint='Không rõ tác giả',nameHint=''){
  const name=nameHint||file.name.replace(/\.[^.]+$/,'')||file.name;
  const same=await findMusicSameName(name);
  const incomingReview=itemLooksLikeReviewName(file.name)||itemLooksLikeReviewName(name);
  const existingFull=same.filter(musicHasLocalAudio).sort((a,b)=>musicFullScore(b)-musicFullScore(a)||((Number(b.size)||0)-(Number(a.size)||0)))[0]||null;
  if(incomingReview&&existingFull){return {id:existingFull.id,synced:true,keptFull:true};}
  const id=await storeFile(file,'Music');
  const fresh=await getItem(id);
  if(same.length){
    const metaSource=same.slice().sort((a,b)=>musicMetaRichness(b)-musicMetaRichness(a)||((b.createdAt||0)-(a.createdAt||0)))[0];
    fresh.name=metaSource?.name||name;
    fresh.author=metaSource?.author||authorHint||'Không rõ tác giả';
    fresh.description=metaSource?.description||'';
    fresh.lyrics=metaSource?.lyrics||'';
    fresh.coverBlob=metaSource?.coverBlob;
    fresh.coverBlob2=metaSource?.coverBlob2;
    fresh.musicOrder=metaSource?.musicOrder??0;
    fresh.source='full';fresh.remoteUrl='';fresh.syncedAt=Date.now();fresh.fullFileName=file.name;
    const wasCurrent=same.some(x=>x.id===musicCurrentId), audio=document.getElementById('musicAudio'), oldTime=audio?.currentTime||0;
    for(const old of same)try{await del(old.id)}catch(_){ }
    await saveMeta(fresh);
    if(wasCurrent){musicCurrentId=fresh.id;try{await playMusicItem(fresh);if(oldTime>0&&audio)audio.currentTime=Math.min(oldTime,audio.duration||oldTime)}catch(_){}}
    return {id:fresh.id,synced:true};
  }
  fresh.name=name;fresh.author=authorHint;fresh.source='full';fresh.remoteUrl='';fresh.musicOrder=(await getMusicItems()).length;await saveMeta(fresh);return {id:fresh.id,synced:false};
}

async function runMusicSyncButton(btn){if(!btn||btn.disabled)return;const old=btn.textContent;const st=document.getElementById('musicSyncStatus');btn.disabled=true;btn.textContent='⟳ ĐANG ĐỒNG BỘ…';if(st)st.textContent='Đang quét toàn bộ nhạc và xóa các bản trùng tên…';try{const removed=await syncAllSameNameMusic();await renderMusicList();const msg=removed?'✓ Đã xóa '+removed+' bản trùng — mỗi tên bài còn 1 sound.':'✓ Đã kiểm tra xong — mỗi tên bài chỉ giữ 1 sound.';btn.textContent='✓ ĐÃ ĐỒNG BỘ';if(st)st.textContent=msg;setTimeout(()=>{btn.textContent=old;btn.disabled=false},2200)}catch(err){console.error(err);btn.textContent='✕ LỖI';if(st)st.textContent='Không thể đồng bộ: '+(err?.message||'lỗi không xác định');setTimeout(()=>{btn.textContent=old;btn.disabled=false},2200)}}
document.getElementById('musicSyncTopBtn2').onclick=()=>runMusicSyncButton(document.getElementById('musicSyncTopBtn2'));document.getElementById('musicUploadBtn').onclick=()=>showModal('musicUploadModal');document.getElementById('musicFileChoice').onclick=()=>openPicker(document.getElementById('musicInput'));document.getElementById('musicInput').onchange=async e=>{const files=[...e.target.files||[]].filter(f=>f.type.startsWith('audio/'));let added=0,synced=0;for(const f of files){try{const r=await saveOrSyncMusicFile(f);added++;if(r.synced)synced++}catch(err){console.error(err)}}document.getElementById('musicUploadStatus').textContent=`Đã xử lý ${added}/${files.length} bài${synced?' · đồng bộ full với '+synced+' bài review':''}.`;await syncAllSameNameMusic();await renderMusicList();if(added)setTimeout(()=>hideModal('musicUploadModal'),700);e.target.value=''};
document.getElementById('musicList').onclick=async e=>{const delBtn=e.target.closest('[data-music-delete]');if(delBtn){e.stopPropagation();const item=await getItem(+delBtn.dataset.musicDelete);if(!item)return;const ok=confirm('Xóa bài "'+musicMetaName(item)+'"?\n\nBài và file âm thanh sẽ bị xóa khỏi bộ nhớ website.');if(!ok)return;const wasCurrent=musicCurrentId===item.id;if(wasCurrent){try{musicAudio.pause()}catch(_){}musicAudio.removeAttribute('src');try{musicAudio.load()}catch(_){}musicCurrentId=null;clearMusicProgress();app.classList.remove('music-playing');if(musicEnabled){v2.muted=false;v2.volume=1;try{await v2.play()}catch(_){} }}await del(item.id);await renderMusicList();return}const edit=e.target.closest('[data-music-edit]');if(edit){e.stopPropagation();const item=await getItem(+edit.dataset.musicEdit);if(item)openMusicEdit(item);return}const play=e.target.closest('[data-music-play]');if(play){e.stopPropagation();const item=await getItem(+play.dataset.musicPlay);if(item){if(musicCurrentId===item.id&&!document.getElementById('musicAudio').paused){document.getElementById('musicAudio').pause();if(musicEnabled){v2.muted=false;v2.volume=1;try{await v2.play()}catch(_){}}renderMusicList()}else await playMusicItem(item)}return}const row=e.target.closest('[data-music-id]');if(row){const item=await getItem(+row.dataset.musicId);if(item)await playMusicItem(item)}};
document.getElementById('musicPlayBtn').onclick=()=>{document.getElementById('musicModeMenu').classList.toggle('hidden')};document.getElementById('musicNormalMode').onclick=async()=>{musicRandom=false;musicPlayed.clear();document.getElementById('musicModeMenu').classList.add('hidden');const items=await getMusicItems();if(items.length)await playMusicItem(items[0]);};document.getElementById('musicRandomMode').onclick=async()=>{musicRandom=true;musicPlayed.clear();document.getElementById('musicModeMenu').classList.add('hidden');const items=await getMusicItems();if(items.length){const first=items[Math.floor(Math.random()*items.length)];musicPlayed.add(first.id);await playMusicItem(first,true)}};
let miniPointerId=null,miniStartX=0,miniStartY=0,miniDx=0,miniDy=0,miniDragging=false;
function resetMiniGesture(){const mini=document.getElementById('musicMini');mini.classList.remove('swiping');mini.style.transform='';mini.style.opacity='';miniPointerId=null;miniDx=0;miniDy=0;miniDragging=false}
function hideMiniBySwipe(dir){const mini=document.getElementById('musicMini');if(!mini)return;app.classList.remove('music-playing');mini.classList.remove('swiping','swipe-away-left','swipe-away-right');mini.classList.add(dir==='left'?'swipe-away-left':'swipe-away-right');setTimeout(()=>{mini.classList.add('hidden');mini.classList.remove('swipe-away-left','swipe-away-right');mini.style.transform='';mini.style.opacity=''},430)}
function stopMusicFromMiniSwipe(){const mini=document.getElementById('musicMini'),a=document.getElementById('musicAudio');if(!mini||!a)return;try{a.pause()}catch(_){}musicCurrentId=null;clearMusicProgress();app.classList.remove('music-playing');mini.classList.remove('swiping');mini.classList.add('swipe-stop-down');setTimeout(()=>{mini.classList.add('hidden');mini.classList.remove('swipe-stop-down');mini.style.transform='';mini.style.opacity=''},590);if(musicEnabled){v2.muted=false;v2.volume=1;try{v2.play()}catch(_){}}renderMusicList()}
const miniEl=document.getElementById('musicMini');if(miniEl){miniEl.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;miniPointerId=e.pointerId;miniStartX=e.clientX;miniStartY=e.clientY;miniDx=miniDy=0;miniDragging=true;miniEl.classList.add('swiping');try{miniEl.setPointerCapture(e.pointerId)}catch(_){}e.preventDefault()});miniEl.addEventListener('pointermove',e=>{if(!miniDragging||e.pointerId!==miniPointerId)return;miniDx=e.clientX-miniStartX;miniDy=e.clientY-miniStartY;if(Math.abs(miniDx)<Math.abs(miniDy)){const dy=Math.max(0,miniDy);miniEl.style.transform=`translate(-50%,${Math.min(125,dy)}px) scale(${Math.max(.94,1-dy/900)})`;miniEl.style.opacity=String(Math.max(.25,1-dy/160))}else{miniEl.style.transform=`translate(calc(-50% + ${miniDx}px),0) rotate(${Math.max(-3,Math.min(3,miniDx/90))}deg)`;miniEl.style.opacity=String(Math.max(.2,1-Math.abs(miniDx)/260))}});const end=e=>{if(!miniDragging||e.pointerId!==miniPointerId)return;const dx=miniDx,dy=miniDy;try{miniEl.releasePointerCapture(e.pointerId)}catch(_){}miniDragging=false;miniPointerId=null;miniEl.classList.remove('swiping');if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy)){hideMiniBySwipe(dx<0?'left':'right')}else if(dy>75&&dy>Math.abs(dx)){stopMusicFromMiniSwipe()}else resetMiniGesture()};miniEl.addEventListener('pointerup',end);miniEl.addEventListener('pointercancel',end)}
document.getElementById('miniPlay').onclick=()=>toggleMusicPlayback();const musicAudio=document.getElementById('musicAudio'),musicProgress=document.getElementById('musicProgress');function updateMusicProgress(){const d=musicAudio.duration||0,t=musicAudio.currentTime||0;document.getElementById('musicCurrentTime').textContent=formatTime(t);document.getElementById('musicDuration').textContent=formatTime(d);musicProgress.value=d?Math.round(t/d*1000):0;updateLyricsHighlight()}function clearMusicProgress(){document.getElementById('musicCurrentTime').textContent='0:00';document.getElementById('musicDuration').textContent='0:00';musicProgress.value=0;const lp=document.getElementById('musicLyrics');if(lp){lp.classList.add('hidden');lp._lyrics=[]}}musicAudio.addEventListener('timeupdate',updateMusicProgress);musicAudio.addEventListener('loadedmetadata',async()=>{updateMusicProgress();if(musicCurrentId!==null){const it=await getItem(musicCurrentId);if(it)await renderLyrics(it)}});musicProgress.addEventListener('input',()=>{const d=musicAudio.duration||0;if(d)musicAudio.currentTime=(Number(musicProgress.value)/1000)*d});document.getElementById('musicAudio').addEventListener('ended',()=>playNextMusic());document.getElementById('musicAudio').addEventListener('play',async()=>{const cur=(await getMusicItems()).find(x=>x.id===musicCurrentId);if(cur)showMiniMusic(cur);v2.muted=true;v2.volume=0;renderMusicList()});document.getElementById('musicAudio').addEventListener('pause',async()=>{if(musicEnabled&&musicCurrentId!==null&&!window.__musicPausedByToggle){v2.muted=false;v2.volume=1;try{await v2.play()}catch(_){}}renderMusicList()});
document.getElementById('musicSearchBtn').onclick=()=>{const p=document.getElementById('musicSearchPanel');p.classList.toggle('hidden');if(!p.classList.contains('hidden'))document.getElementById('musicWebQuery').focus()};document.getElementById('musicWebGo').onclick=()=>renderMusicSearch(document.getElementById('musicWebQuery').value.trim());document.getElementById('musicWebQuery').addEventListener('input',e=>{clearTimeout(musicSearchTimer);const q=e.target.value.trim();musicSearchTimer=setTimeout(()=>renderMusicSearch(q),280)});document.getElementById('musicWebQuery').addEventListener('keydown',e=>{if(e.key==='Enter')renderMusicSearch(e.target.value.trim())});document.getElementById('musicSearchResults').onclick=async e=>{const add=e.target.closest('[data-preview-add]');if(add){const item={name:add.dataset.previewName||'Preview',author:add.dataset.previewAuthor||'Không rõ tác giả',description:'Preview online',category:'Music',rank:'',source:'review',type:'audio/mpeg',size:0,createdAt:Date.now(),remoteUrl:add.dataset.previewUrl||'',musicOrder:(await getMusicItems()).length};if(add.dataset.previewCover){try{const r=await fetch(add.dataset.previewCover);if(r.ok)item.coverBlob=await r.blob()}catch(_){}}await saveMeta(item);await renderMusicList();return}const b=e.target.closest('[data-preview-url]');if(!b||!musicEnabled)return;const a=document.getElementById('musicAudio');if(a.dataset.url)try{URL.revokeObjectURL(a.dataset.url)}catch(_){}a.src=b.dataset.previewUrl;musicCurrentId=null;await stopBackgroundVideo();try{await a.play()}catch(_){}};
function pickMusicCover(which){openPicker(document.getElementById(which==='one'?'musicCover1Input':'musicCover2Input'))}document.getElementById('musicCover1Pick').onclick=()=>pickMusicCover('one');document.getElementById('musicCover2Pick').onclick=()=>pickMusicCover('two');document.getElementById('musicCover1Remove').onclick=()=>{pendingMusicCover1=null;setMusicPreview('musicCover1Preview',null)};document.getElementById('musicCover2Remove').onclick=()=>{pendingMusicCover2=null;setMusicPreview('musicCover2Preview',null)};document.getElementById('musicCover1Input').onchange=async e=>{const f=e.target.files?.[0];if(f){pendingMusicCover1=new Blob([await f.arrayBuffer()],{type:f.type});setMusicPreview('musicCover1Preview',pendingMusicCover1)}e.target.value=''};document.getElementById('musicCover2Input').onchange=async e=>{const f=e.target.files?.[0];if(f){pendingMusicCover2=new Blob([await f.arrayBuffer()],{type:f.type});setMusicPreview('musicCover2Preview',pendingMusicCover2)}e.target.value=''};document.getElementById('musicSaveEdit').onclick=async()=>{const item=await getItem(musicEditId);if(!item)return;const oldName=item.name;item.name=document.getElementById('musicEditName').value.trim()||item.name;item.author=document.getElementById('musicEditAuthor').value.trim()||'Không rõ tác giả';item.lyrics=document.getElementById('musicEditLyrics').value.trim();if(pendingMusicCover1===null)delete item.coverBlob;else item.coverBlob=pendingMusicCover1;if(pendingMusicCover2===null)delete item.coverBlob2;else item.coverBlob2=pendingMusicCover2;await saveMeta(item);await syncAllSameNameMusic();hideModal('musicEditModal');await renderMusicList();if(musicCurrentId===item.id)showMiniMusic(item);};
document.getElementById('musicDeleteEdit').onclick=async()=>{const item=await getItem(musicEditId);if(!item)return;const ok=confirm(`Xóa bài "${musicMetaName(item)}" khỏi Music?\n\nFile âm thanh và dữ liệu của bài này sẽ bị xóa khỏi bộ nhớ website.`);if(!ok)return;const wasCurrent=musicCurrentId===item.id;if(wasCurrent){try{musicAudio.pause()}catch(_){}musicAudio.removeAttribute('src');try{musicAudio.load()}catch(_){}musicCurrentId=null;clearMusicProgress();app.classList.remove('music-playing');if(musicEnabled){v2.muted=false;v2.volume=1;try{await v2.play()}catch(_){} }}await del(item.id);musicEditId=null;pendingMusicCover1=null;pendingMusicCover2=null;hideModal('musicEditModal');await renderMusicList();};
// Create song
function scaffoldLyrics(text,duration){const lines=String(text||'').split('\n').map(x=>x.trim()).filter(Boolean).filter(x=>!/^(\[\d{1,2}:\d{2}(?:\.\d{1,3})?\])/.test(x));if(!lines.length)return '';const d=Number(duration)||lines.length*5;const step=d/lines.length;return lines.map((x,i)=>{const t=Math.floor(i*step),m=Math.floor(t/60),sec=(t%60).toString().padStart(2,'0');return `[${m}:${sec}] ${x}`}).join('\n')}
document.getElementById('musicCreateBtn').onclick=()=>showModal('musicCreateModal');let createAudioFile=null,createCover1=null,createCover2=null;document.getElementById('musicCreateAudioPick').onclick=()=>openPicker(document.getElementById('musicCreateAudio'));document.getElementById('musicCreateAudio').onchange=e=>{createAudioFile=e.target.files?.[0]||null;document.getElementById('musicCreateAudioLabel').textContent=createAudioFile?createAudioFile.name:'Chưa chọn file'};document.getElementById('musicCreateCover1Pick').onclick=()=>openPicker(document.getElementById('musicCreateCover1'));document.getElementById('musicCreateCover2Pick').onclick=()=>openPicker(document.getElementById('musicCreateCover2'));document.getElementById('musicCreateCover1Remove').onclick=()=>{createCover1=null;setMusicPreview('musicCreateCover1Preview',null)};document.getElementById('musicCreateCover2Remove').onclick=()=>{createCover2=null;setMusicPreview('musicCreateCover2Preview',null)};document.getElementById('musicCreateCover1').onchange=async e=>{const f=e.target.files?.[0];if(f){createCover1=new Blob([await f.arrayBuffer()],{type:f.type});setMusicPreview('musicCreateCover1Preview',createCover1)}e.target.value=''};document.getElementById('musicCreateCover2').onchange=async e=>{const f=e.target.files?.[0];if(f){createCover2=new Blob([await f.arrayBuffer()],{type:f.type});setMusicPreview('musicCreateCover2Preview',createCover2)}e.target.value=''};document.getElementById('musicCreateSave').onclick=async()=>{const name=document.getElementById('musicCreateName').value.trim();const author=document.getElementById('musicCreateAuthor').value.trim();const st=document.getElementById('musicCreateStatus');if(!name||!createAudioFile){st.textContent='Cần tên bài hát và file audio.';return}try{const result=await saveOrSyncMusicFile(createAudioFile,author||'Không rõ tác giả',name);const id=result.id;const item=await getItem(id);item.name=name;item.author=author||item.author||'Không rõ tác giả';item.lyrics=document.getElementById('musicCreateLyrics').value.trim();item.musicOrder=(await getMusicItems()).length;item.coverBlob=createCover1||undefined;item.coverBlob2=createCover2||undefined;await saveMeta(item);st.textContent='Đã tạo bài hát.';await renderMusicList();setTimeout(()=>hideModal('musicCreateModal'),500)}catch(err){st.textContent='Không thể tạo bài hát: '+(err?.message||'lỗi');}};
document.getElementById('musicCreateAutoLyric').onclick=async()=>{const raw=document.getElementById('musicCreateLyrics').value.trim();if(!raw){document.getElementById('musicCreateLyrics').focus();return}document.getElementById('musicCreateLyrics').value=scaffoldLyrics(raw,180)};document.getElementById('musicEditAutoLyric').onclick=async()=>{const raw=document.getElementById('musicEditLyrics').value.trim();if(!raw){document.getElementById('musicEditLyrics').focus();return}const a=document.getElementById('musicAudio');document.getElementById('musicEditLyrics').value=scaffoldLyrics(raw,a.duration||180)};document.getElementById('backgroundPickBtn').onclick=()=>openPicker(document.getElementById('backgroundInput'));document.getElementById('backgroundInput').onchange=async e=>{const f=e.target.files?.[0];if(f)try{await setBackgroundVideo(f)}catch(err){alert('Không thể thay video nền: '+(err?.message||'lỗi'))}e.target.value=''};document.getElementById('backgroundResetBtn').onclick=()=>resetBackgroundVideo();
refreshStorageUI();
function playPageTransition(){const el=document.getElementById('pageTransition');if(!el)return;el.classList.remove('run');void el.offsetWidth;el.classList.add('run');window.clearTimeout(window.__pageFxTimer);window.__pageFxTimer=window.setTimeout(()=>{el.classList.remove('run');el.style.visibility='hidden';el.style.opacity='0'},2450)}
form.addEventListener('submit',async e=>{e.preventDefault();if(pw.value===PASSWORD){sessionStorage.setItem('rezeUnlocked','1');document.querySelector('.access')?.classList.remove('show');sessionStorage.removeItem('wrong');stopVideo1();showRandomHomeQuote();uiSound('open');playPageTransition();login.classList.add('leaving');app.classList.remove('hidden');app.classList.add('reveal');window.scrollTo(0,0);document.documentElement.scrollTop=0;document.body.scrollTop=0;await ensureVideo2Playing();setTimeout(()=>{login.classList.add('hidden');login.classList.remove('leaving');app.classList.remove('reveal');window.scrollTo(0,0);document.documentElement.scrollTop=0;document.body.scrollTop=0;},2420);}else{let n=+(sessionStorage.getItem('wrong')||0)+1;sessionStorage.setItem('wrong',n);status.className='status error';if(n%10===0)status.textContent='Sai mật khẩu — khóa 30 giây.';else status.textContent='Sai mật khẩu — lần thử '+n;pw.select()}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b&&!b.dataset.noUiSound)uiSound(b.classList.contains('primary')?'open':'tap')},{capture:true});
window.addEventListener('pointerdown',()=>{if(!app.classList.contains('hidden'))ensureVideo2Playing()},{passive:true});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&!app.classList.contains('hidden'))ensureVideo2Playing()});
window.addEventListener('pageshow',()=>{if(!app.classList.contains('hidden'))ensureVideo2Playing()});
async function startVideo1WithAudio(){
  v1.loop=true;v1.playsInline=true;v1.preload='auto';v1.volume=1;v1.muted=false;try{v1.load()}catch(_){}
  try{await v1.play();document.getElementById('video1SoundHint')?.classList.add('hidden')}catch(e){
    // Mobile browsers may block audible autoplay until a gesture; keep animation playing silently and show a one-tap sound control.
    v1.muted=true;v1.volume=0;try{await v1.play()}catch(_e){}
    document.getElementById('video1SoundHint')?.classList.remove('hidden');
  }
}
v1.addEventListener('click',async()=>{uiSound('tap');v1.muted=false;v1.volume=1;try{await v1.play();document.getElementById('video1SoundHint')?.classList.add('hidden')}catch(e){}});
document.getElementById('video1SoundHint')?.addEventListener('click',async e=>{e.stopPropagation();v1.muted=false;v1.volume=1;try{await v1.play();document.getElementById('video1SoundHint')?.classList.add('hidden')}catch(e){}});
function applyCategoryOrder(){const grid=document.getElementById('categoryGrid');if(!grid)return;const saved=JSON.parse(localStorage.getItem(CAT_ORDER_KEY)||'null');if(!Array.isArray(saved)||!saved.length)return;const map=new Map([...grid.children].map(x=>[x.dataset.cat,x]));saved.forEach(cat=>{const el=map.get(cat);if(el)grid.appendChild(el)})}
function routeHash(){const h=decodeURIComponent(location.hash.slice(1));if(!h)return; if(h==='home'){switchView('homeView');return}if(h==='search'){switchView('searchView');renderSearch();return}if(h==='music'){switchView('musicView');renderMusicList();return}if(h==='achievements'){switchView('achievementsView');renderAchievements();return}if(h==='you'){switchView('youView');return}if(h.startsWith('category:')){openCategory(h.slice(9));return}}window.addEventListener('hashchange',routeHash);(async()=>{syncMusicButton();await prepareStorage();await openDB();await syncAllSameNameMusic();await loadBackgroundVideo();if(sessionStorage.getItem('rezeUnlocked')==='1'){stopVideo1();login.classList.add('hidden');app.classList.remove('hidden');await ensureVideo2Playing();showRandomHomeQuote();setTimeout(routeHash,0)}else{startVideo1WithAudio();setTimeout(()=>document.querySelector('.access')?.classList.add('show'),3000)}})();
})();
